collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7204301
color:
  saturation: 0.7132617
  brandStrength: 1
  lightness: 0.483871
  brandColors:
    - '#35241C'
    - '#838F83'
    - '#FFFFF8'
    - '#C5C9B8'
    - '#E53D2B'
  rhythmicContrast: 0.8530466
layout_spectrum: 0.7867383
name: 'J. Woods Production '
